[package]
name = "webwpa"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny_http = { version = "0.12.0", optional = true }
tungstenite = "0.20.0"
wpactrl = "0.5.1"

[features]
default = ["webserver"]
webserver = ["dep:tiny_http"]
